# Generated by Django 3.0.5 on 2020-04-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200414_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start',
            field=models.CharField(max_length=10),
        ),
    ]
