# Generated by Django 3.0.5 on 2020-04-26 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='bookings',
            new_name='fav_color',
        ),
    ]
