# Generated by Django 3.0.5 on 2020-04-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200429_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='username',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
